services:
  - type: web
    name: habynex-recommendations-start
    runtime: python

    buildCommand: |
      python3.10 -m pip install --upgrade pip
      python3.10 -m pip install -r requirements.txt

    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app

    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
